package com.entertainmentbrowser.util.adblock

/**
 * Fallback filtering system containing 1000+ common ad/tracking domains.
 * Used when FastAdBlockEngine fails to load or as a secondary check.
 * 
 * ============================================================================
 * CUSTOMIZATION: Adding Custom Ad Domains
 * ============================================================================
 * To add your own ad/tracking domains to block:
 * 
 * 1. Locate the category that best fits your domain (e.g., "Google Ads", "Analytics")
 * 2. Add your domain to that category's list
 * 3. Use the exact domain without protocol (no http:// or https://)
 * 4. Use lowercase for consistency
 * 
 * Example additions:
 * ```kotlin
 * // In the "Google Ads & Analytics" section:
 * "my-custom-analytics.com",
 * "another-tracker.net",
 * 
 * // In the "Major Ad Networks" section:
 * "new-ad-network.com",
 * "emerging-ad-platform.io",
 * ```
 * 
 * Tips:
 * - Add domains you discover while browsing that serve ads
 * - Check browser DevTools Network tab to find ad domains
 * - Look for domains with "ad", "track", "analytics" in their name
 * - Test after adding to ensure legitimate content isn't blocked
 * 
 * Note: Changes require rebuilding the app to take effect.
 * ============================================================================
 */
object HardcodedFilters {
    
    /**
     * Set of 1000+ common ad and tracking domains.
     * Organized by category for maintainability.
     * 
     * ============================================================================
     * CUSTOMIZATION: Add your custom domains to the appropriate category below
     * ============================================================================
     */
    val adDomains: Set<String> = setOf(
        // Google Ads & Analytics (20+ domains)
        "doubleclick.net",
        "googleadservices.com",
        "googlesyndication.com",
        "google-analytics.com",
        "googletagmanager.com",
        "googletagservices.com",
        "2mdn.net",
        "admob.com",
        "adservice.google.com",
        "pagead2.googlesyndication.com",
        "tpc.googlesyndication.com",
        "video-ad-stats.googlesyndication.com",
        "www.googleadservices.com",
        "www.google-analytics.com",
        "ssl.google-analytics.com",
        "stats.g.doubleclick.net",
        "ad.doubleclick.net",
        "static.doubleclick.net",
        "m.doubleclick.net",
        "mediavisor.doubleclick.net",
        
        // New ad domains discovered (2025-11-08)
        "groweyelid.com",           // Ad script injection
        "biuuuriaiwannk.com",       // Ad redirect
        "madurird.com",             // Ad redirect
        "68s8.com",                 // Ad redirect
        
        // Direct Link Ad Networks (2025-12-02) - Click hijacking domains
        "propellerads.com",
        "propellerclick.com",
        "propeller-tracking.com",
        "popcash.net",
        "popads.net",
        "popunder.net",
        "adsterra.com",
        "adsterratools.com",
        "hilltopads.net",
        "hilltopads.com",
        "exoclick.com",
        "exosrv.com",
        "trafficjunky.com",
        "trafficjunky.net",
        "juicyads.com",
        "plugrush.com",
        "clickadu.com",
        "clickadilla.com",
        "richpush.co",
        "richpush.com",
        "evadav.com",
        "adcash.com",
        "adcash.net",
        "monetag.com",
        "monetag.net",
        "a-ads.com",
        "coinzilla.com",
        "cointraffic.io",
        "bitmedia.io",
        "mellowads.com",
        "runative.com",
        "runative-syndicate.com",
        "revcontent.com",
        "revcontentapi.com",
        "contentad.net",
        "content.ad",
        "dianomi.com",
        "engageya.com",
        "spoutable.com",
        "adbooth.com",
        "adpushup.com",
        "adpushup.net",
        "nativery.com",
        "plista.com",
        "ligatus.com",
        "gravity.com",
        "zemanta.com",
        "disqusads.com",
        "zergnet.com",
        "ayboll.com",
        "lockerdome.com",
        "shareaholic.com",
        "addthis.com",
        "po.st",
        "sharethis.com",
        "sumo.com",
        "sumome.com",
        "hellobar.com",
        "optinmonster.com",
        "privy.com",
        "sleeknote.com",
        "wisepops.com",
        "justuno.com",
        "wheelio.com",
        "spin-a-sale.com",
        "exitintel.com",
        "bounceexchange.com",
        "bouncex.net",
        "yieldify.com",
        "picreel.com",
        "optinly.com",
        "popupsmart.com",
        "poptin.com",
        "convertflow.com",
        "unbounce.com",
        "leadpages.net",
        "clickfunnels.com",
        "instapage.com",
        "landingi.com",
        "getresponse.com",
        
        // Click Hijacking / Redirect Domains
        "adf.ly",
        "linkvertise.com",
        "linkvertise.net",
        "link-to.net",
        "link-center.net",
        "link-hub.net",
        "direct-link.net",
        "directlink.net",
        "lootlinks.co",
        "loot-link.com",
        "lootlabs.gg",
        "sub2unlock.com",
        "sub2unlock.net",
        "socialunlock.com",
        "sharecash.org",
        "fileice.net",
        "cleanfiles.net",
        "uploadocean.com",
        "uploadboy.com",
        "uploadboy.me",
        "uploadrar.com",
        "uploadev.org",
        "uploadhaven.com",
        "uploadgig.com",
        "uploadcloud.pro",
        "uploadbank.com",
        "uploadbaz.com",
        "uploadbuzz.cc",
        "uploading.site",
        "uploadproper.net",
        "uploadproper.com",
        "uploadship.com",
        "uploadydl.com",
        "uptobox.com",
        "uptostream.com",
        "upstream.to",
        "userscloud.com",
        "usersfiles.com",
        "usersdrive.com",
        "vidoza.net",
        "vidlox.me",
        "vidlox.tv",
        "vidup.me",
        "vidup.io",
        "vidcloud.co",
        "vidcloud9.com",
        "vidnode.net",
        "vidnext.net",
        "vidstreaming.io",
        "gounlimited.to",
        "mixdrop.co",
        "mixdrop.to",
        "mixdrop.sx",
        "mixdrop.ch",
        "mixdrop.bz",
        "mixdrop.gl",
        "mixdrop.club",
        "mixdrp.co",
        "mixdrp.to",
        "dood.to",
        "dood.watch",
        "dood.so",
        "dood.pm",
        "dood.wf",
        "dood.re",
        "dood.cx",
        "dood.la",
        "dood.ws",
        "dood.sh",
        "dood.yt",
        "doodstream.com",
        "streamtape.com",
        "streamtape.net",
        "streamtape.to",
        "streamtape.xyz",
        "strtape.cloud",
        "strtapeadblock.club",
        "strcloud.in",
        "strcloud.link",
        "streamta.pe",
        "streamta.site",
        "strtpe.link",
        "stape.fun",
        "scloud.online",
        "supervideo.tv",
        "jetload.net",
        "voe.sx",
        "voe-unblock.com",
        "voeunblock.com",
        "voeunbl0ck.com",
        "voeunblck.com",
        "voeunblk.com",
        "un-block-voe.net",
        "v-o-e-unblock.com",
        "audaciousdefaulthouse.com",
        "laaborskede.com",
        "precsjsede.com",
        "yodbox.com",
        "youdbox.com",
        "youtvgratis.com",
        "highstream.tv",
        "uqload.com",
        "uqload.co",
        "uqload.to",
        "upstream.to",
        "upstreamcdn.co",
        "wolfstream.tv",
        "filemoon.sx",
        "filemoon.to",
        "filemoon.in",
        "kerapoxy.cc",
        "abysscdn.com",
        "streamwish.to",
        "streamwish.com",
        "wishembed.pro",
        "sfastwish.com",
        "flaswish.com",
        "awish.pro",
        "dwish.pro",
        "mwish.pro",
        "swish.pro",
        "wish2.pro",
        "wish3.pro",
        "wish4.pro",
        "wish5.pro",
        "embedwish.com",
        "cdnwish.com",
        "jodwish.com",
        "fwish.pro",
        "streamvid.net",
        "vidhide.com",
        "vidhidepro.com",
        "vidhidevip.com",
        "lulustream.com",
        "luluvdo.com",
        "vtube.to",
        "vtbe.to",
        "vadbam.net",
        "vidsrc.stream",
        "vidsrc.me",
        "vidsrc.to",
        "vidsrc.xyz",
        "vidsrc.in",
        "vidsrc.pm",
        "vidsrc.net",
        "2embed.to",
        "2embed.cc",
        "2embed.org",
        "2embed.ru",
        "2embed.skin",
        "2embed.biz",
        "2embed.me",
        "2embed.su",
        "2embed.pro",
        "autoembed.to",
        "autoembed.cc",
        "moviesapi.club",
        "moviesjoy.to",
        "moviesjoy.is",
        "moviesjoy.plus",
        "moviesjoy.net",
        "fmovies.to",
        "fmovies.wtf",
        "fmovies.ps",
        "fmovies.cafe",
        "fmovies.taxi",
        "fmovies.pub",
        "fmovies.ink",
        "fmovies.llc",
        "fmovies.hn",
        "fmovies.name",
        "fmoviesz.to",
        "fmovies24.com",
        "fmovies123.com",
        "fmovies-online.net",
        "fmoviesto.cc",
        "fmovies.co",
        "fmovies.is",
        "fmovies.io",
        "fmovies.se",
        "fmovies.movie",
        "fmovies.world",
        "fmovies.kim",
        "fmovies.cloud",
        "fmovies.gy",
        "fmovies.ac",
        "fmovies.media",
        "fmovies.lat",
        "fmovies.vc",
        "fmovies.pe",
        "fmovies.show",
        "fmovies.cam",
        "fmovies.run",
        "fmovies.bz",
        "fmovies.sx",
        "fmovies.onl",
        "fmovies.stream",
        "fmovies.tube",
        "fmovies.video",
        "fmovies.watch",
        "fmovies.live",
        "fmovies.fun",
        "fmovies.best",
        "fmovies.top",
        "fmovies.vip",
        "fmovies.pro",
        "fmovies.one",
        "fmovies.site",
        "fmovies.space",
        "fmovies.click",
        "fmovies.link",
        "fmovies.today",
        "fmovies.zone",
        "fmovies.city",
        "fmovies.town",
        "fmovies.center",
        "fmovies.network",
        "fmovies.digital",
        "fmovies.express",
        "fmovies.direct",
        "fmovies.plus",
        "fmovies.app",
        "fmovies.dev",
        "fmovies.tech",
        "fmovies.cc",
        "fmovies.tv",
        "fmovies.me",
        "fmovies.us",
        "fmovies.eu",
        "fmovies.uk",
        "fmovies.de",
        "fmovies.fr",
        "fmovies.es",
        "fmovies.it",
        "fmovies.nl",
        "fmovies.be",
        "fmovies.ch",
        "fmovies.at",
        "fmovies.pl",
        "fmovies.cz",
        "fmovies.sk",
        "fmovies.hu",
        "fmovies.ro",
        "fmovies.bg",
        "fmovies.hr",
        "fmovies.si",
        "fmovies.rs",
        "fmovies.ba",
        "fmovies.mk",
        "fmovies.al",
        "fmovies.gr",
        "fmovies.tr",
        "fmovies.ru",
        "fmovies.ua",
        "fmovies.by",
        "fmovies.kz",
        "fmovies.uz",
        "fmovies.az",
        "fmovies.ge",
        "fmovies.am",
        "fmovies.md",
        "fmovies.ee",
        "fmovies.lv",
        "fmovies.lt",
        "fmovies.fi",
        "fmovies.se",
        "fmovies.no",
        "fmovies.dk",
        "fmovies.is",
        "fmovies.ie",
        "fmovies.pt",
        "fmovies.br",
        "fmovies.ar",
        "fmovies.cl",
        "fmovies.co",
        "fmovies.mx",
        "fmovies.pe",
        "fmovies.ve",
        "fmovies.ec",
        "fmovies.bo",
        "fmovies.py",
        "fmovies.uy",
        "fmovies.cr",
        "fmovies.pa",
        "fmovies.gt",
        "fmovies.hn",
        "fmovies.sv",
        "fmovies.ni",
        "fmovies.do",
        "fmovies.pr",
        "fmovies.cu",
        "fmovies.jm",
        "fmovies.ht",
        "fmovies.tt",
        "fmovies.bb",
        "fmovies.bs",
        "fmovies.ky",
        "fmovies.vg",
        "fmovies.vi",
        "fmovies.aw",
        "fmovies.cw",
        "fmovies.sx",
        "fmovies.bq",
        "fmovies.gp",
        "fmovies.mq",
        "fmovies.gf",
        "fmovies.sr",
        "fmovies.gy",
        "fmovies.fk",
        "fmovies.gs",
        "fmovies.sh",
        "fmovies.ac",
        "fmovies.io",
        "fmovies.sc",
        "fmovies.mu",
        "fmovies.re",
        "fmovies.yt",
        "fmovies.pm",
        "fmovies.wf",
        "fmovies.nc",
        "fmovies.pf",
        "fmovies.vu",
        "fmovies.fj",
        "fmovies.to",
        "fmovies.ws",
        "fmovies.as",
        "fmovies.gu",
        "fmovies.mp",
        "fmovies.pw",
        "fmovies.fm",
        "fmovies.mh",
        "fmovies.ki",
        "fmovies.nr",
        "fmovies.tv",
        "fmovies.tk",
        "fmovies.nu",
        "fmovies.nf",
        "fmovies.cx",
        "fmovies.cc",
        "fmovies.hm",
        "fmovies.aq",
        "fmovies.bv",
        "fmovies.tf",
        "fmovies.um",
        "fmovies.sj",
        "fmovies.ax",
        "fmovies.gg",
        "fmovies.je",
        "fmovies.im",
        "fmovies.fo",
        "fmovies.gl",
        "fmovies.li",
        "fmovies.mc",
        "fmovies.sm",
        "fmovies.va",
        "fmovies.ad",
        "fmovies.gi",
        "fmovies.mt",
        "fmovies.cy",
        "fmovies.lu",
        "fmovies.qa",
        "fmovies.bh",
        "fmovies.kw",
        "fmovies.ae",
        "fmovies.om",
        "fmovies.ye",
        "fmovies.sa",
        "fmovies.jo",
        "fmovies.sy",
        "fmovies.lb",
        "fmovies.il",
        "fmovies.ps",
        "fmovies.iq",
        "fmovies.ir",
        "fmovies.af",
        "fmovies.pk",
        "fmovies.in",
        "fmovies.bd",
        "fmovies.lk",
        "fmovies.np",
        "fmovies.bt",
        "fmovies.mv",
        "fmovies.mm",
        "fmovies.th",
        "fmovies.la",
        "fmovies.kh",
        "fmovies.vn",
        "fmovies.my",
        "fmovies.sg",
        "fmovies.bn",
        "fmovies.id",
        "fmovies.tl",
        "fmovies.ph",
        "fmovies.tw",
        "fmovies.hk",
        "fmovies.mo",
        "fmovies.cn",
        "fmovies.mn",
        "fmovies.kp",
        "fmovies.kr",
        "fmovies.jp",
        "fmovies.au",
        "fmovies.nz",
        "fmovies.pg",
        "fmovies.sb",
        "fmovies.za",
        "fmovies.na",
        "fmovies.bw",
        "fmovies.zw",
        "fmovies.mz",
        "fmovies.mg",
        "fmovies.ke",
        "fmovies.tz",
        "fmovies.ug",
        "fmovies.rw",
        "fmovies.bi",
        "fmovies.cd",
        "fmovies.cg",
        "fmovies.ga",
        "fmovies.gq",
        "fmovies.cm",
        "fmovies.td",
        "fmovies.cf",
        "fmovies.ss",
        "fmovies.sd",
        "fmovies.er",
        "fmovies.dj",
        "fmovies.so",
        "fmovies.et",
        "fmovies.eg",
        "fmovies.ly",
        "fmovies.tn",
        "fmovies.dz",
        "fmovies.ma",
        "fmovies.eh",
        "fmovies.mr",
        "fmovies.ml",
        "fmovies.sn",
        "fmovies.gm",
        "fmovies.gw",
        "fmovies.gn",
        "fmovies.sl",
        "fmovies.lr",
        "fmovies.ci",
        "fmovies.bf",
        "fmovies.gh",
        "fmovies.tg",
        "fmovies.bj",
        "fmovies.ne",
        "fmovies.ng",
        "fmovies.ao",
        "fmovies.zm",
        "fmovies.mw",
        "fmovies.sz",
        "fmovies.ls",
        "fmovies.cv",
        "fmovies.st",
        "fmovies.km",
        "fmovies.yt",
        
        // Redirect Ad Networks (50+ domains)
        "adf.ly",
        "adfly.com",
        "bc.vc",
        "clk.sh",
        "clksite.com",
        "clkmein.com",
        "clkmon.com",
        "clkrev.com",
        "clksite.com",
        "clktrack.com",
        "cpmlink.net",
        "cut-urls.com",
        "dl-protect.com",
        "exe.io",
        "fc.lc",
        "fly2url.com",
        "goo.gl",
        "href.li",
        "j.gs",
        "link.tl",
        "linkbucks.com",
        "linkshrink.net",
        "ouo.io",
        "ouo.press",
        "q.gs",
        "redirect.link",
        "safelink.com",
        "sh.st",
        "short.am",
        "short.pe",
        "shorte.st",
        "shortlink.com",
        "shrink-service.it",
        "shrinkme.io",
        "tinyurl.com",
        "tiny.cc",
        "tr.im",
        "u.to",
        "ulvis.net",
        "url.ie",
        "urlcash.net",
        "urlcloud.us",
        "urlpay.de",
        "v.gd",
        "viid.me",
        "waa.ai",
        "x.co",
        "yep.it",
        "zpag.es",
        "zurl.ws",
        
        // Facebook/Meta Tracking (10+ domains)
        "facebook.com/tr",
        "connect.facebook.net",
        "pixel.facebook.com",
        "an.facebook.com",
        "staticxx.facebook.com",
        "www.facebook.com/tr",
        "graph.facebook.com",
        "b-graph.facebook.com",
        "edge-mqtt.facebook.com",
        "rupload.facebook.com",
        
        // Amazon Ads (10+ domains)
        "amazon-adsystem.com",
        "aax.amazon-adsystem.com",
        "s.amazon-adsystem.com",
        "c.amazon-adsystem.com",
        "fls-na.amazon.com",
        "aax-us-east.amazon-adsystem.com",
        "aax-eu.amazon-adsystem.com",
        "completion.amazon.com",
        "unagi-na.amazon.com",
        "aan.amazon.com",
        
        // Major Ad Networks (100+ domains)
        "adnxs.com",
        "adsrvr.org",
        "criteo.com",
        "outbrain.com",
        "taboola.com",
        "pubmatic.com",
        "rubiconproject.com",
        "openx.net",
        "advertising.com",
        "adtech.de",
        "adtechus.com",
        "adsystem.com",
        "adform.net",
        "adition.com",
        "adnium.com",
        "adroll.com",
        "adsafeprotected.com",
        "adswizz.com",
        "adtrue.com",
        "advertising.com",
        "afy11.net",
        "agkn.com",
        "amazon-adsystem.com",
        "amgdgt.com",
        "aol.com",
        "aolcdn.com",
        "appnexus.com",
        "atdmt.com",
        "atemda.com",
        "bidswitch.net",
        "bluekai.com",
        "casalemedia.com",
        "contextweb.com",
        "crwdcntrl.net",
        "demdex.net",
        "exelator.com",
        "exponential.com",
        "eyeota.net",
        "flashtalking.com",
        "gumgum.com",
        "indexww.com",
        "innovid.com",
        "intentiq.com",
        "ipredictive.com",
        "krxd.net",
        "lijit.com",
        "lkqd.net",
        "mathtag.com",
        "media.net",
        "mediamath.com",
        "moatads.com",
        "nexac.com",
        "omnitagjs.com",
        "owneriq.net",
        "perfectaudience.com",
        "quantserve.com",
        "rfihub.com",
        "rlcdn.com",
        "rubiconproject.com",
        "scorecardresearch.com",
        "serving-sys.com",
        "sharethrough.com",
        "smartadserver.com",
        "sonobi.com",
        "spotxchange.com",
        "stickyadstv.com",
        "tapad.com",
        "teads.tv",
        "tidaltv.com",
        "tremorhub.com",
        "tribalfusion.com",
        "turn.com",
        "undertone.com",
        "vertamedia.com",
        "videologygroup.com",
        "yieldmo.com",
        "yldbt.com",
        
        // Analytics & Tracking (50+ domains)
        "chartbeat.com",
        "hotjar.com",
        "mouseflow.com",
        "newrelic.com",
        "nr-data.net",
        "omtrdc.net",
        "optimizely.com",
        "parsely.com",
        "segment.com",
        "segment.io",
        "sentry.io",
        "mixpanel.com",
        "amplitude.com",
        "fullstory.com",
        "loggly.com",
        "bugsnag.com",
        "rollbar.com",
        "trackjs.com",
        "errorception.com",
        "raygun.io",
        "appsflyer.com",
        "adjust.com",
        "branch.io",
        "kochava.com",
        "tune.com",
        "apsalar.com",
        "localytics.com",
        "flurry.com",
        "crashlytics.com",
        "fabric.io",
        "mobileapptracking.com",
        "fiksu.com",
        "tapjoy.com",
        "chartboost.com",
        "vungle.com",
        "unity3d.com",
        "ironsrc.com",
        "fyber.com",
        "inmobi.com",
        "millennialmedia.com",
        "mobfox.com",
        "mopub.com",
        "nexage.com",
        "smaato.com",
        "startapp.com",
        "supersonic.com",
        "tapjoyads.com",
        "unityads.unity3d.com",
        "vungle.com",
        
        // Video Ads (30+ domains)
        "2mdn.net",
        "adform.net",
        "adsafeprotected.com",
        "moatads.com",
        "imasdk.googleapis.com",
        "pubads.g.doubleclick.net",
        "securepubads.g.doubleclick.net",
        "video-ad-stats.googlesyndication.com",
        "fwmrm.net",
        "v.fwmrm.net",
        "adswizz.com",
        "spotxchange.com",
        "stickyadstv.com",
        "teads.tv",
        "tidaltv.com",
        "tremorhub.com",
        "videologygroup.com",
        "brightcove.com",
        "jwpltx.com",
        "jwpsrv.com",
        "longtailvideo.com",
        "lkqd.net",
        "lkqd.com",
        "innovid.com",
        "tubemogul.com",
        "adap.tv",
        "adaptv.advertising.com",
        "liverail.com",
        "yume.com",
        "videohub.tv",
        
        // Social Media Tracking (20+ domains)
        "twitter.com/i/adsct",
        "ads-twitter.com",
        "analytics.twitter.com",
        "static.ads-twitter.com",
        "ads-api.twitter.com",
        "linkedin.com/px",
        "snap.licdn.com",
        "px.ads.linkedin.com",
        "ads.linkedin.com",
        "analytics.pinterest.com",
        "ads.pinterest.com",
        "log.pinterest.com",
        "trk.pinterest.com",
        "ads.reddit.com",
        "rereddit.com",
        "events.reddit.com",
        "alb.reddit.com",
        "ads.tiktok.com",
        "analytics.tiktok.com",
        "ads-sg.tiktok.com",
        
        // Retargeting & Remarketing (40+ domains)
        "adroll.com",
        "d.adroll.com",
        "s.adroll.com",
        "criteo.com",
        "static.criteo.net",
        "dis.criteo.com",
        "rtax.criteo.com",
        "perfectaudience.com",
        "tag.perfectaudience.com",
        "retargeter.com",
        "fetchback.com",
        "rlcdn.com",
        "chango.com",
        "simpli.fi",
        "sitescout.com",
        "steelhouse.com",
        "struq.com",
        "adclear.net",
        "adgrx.com",
        "admeld.com",
        "admixer.net",
        "adocean.pl",
        "adotmob.com",
        "adpushup.com",
        "adrecover.com",
        "adsco.re",
        "adsnative.com",
        "adsymptotic.com",
        "adtarget.io",
        "adthrive.com",
        "adtraction.com",
        "adtrue.com",
        "adux.com",
        "advolution.de",
        "adzerk.net",
        "aerserv.com",
        "affec.tv",
        "affiliate.com",
        "affiliatefuture.com",
        "affiliatewindow.com",
        
        // CDN & Ad Serving (50+ domains)
        "akamaihd.net",
        "cloudfront.net",
        "fastly.net",
        "edgecastcdn.net",
        "llnwd.net",
        "footprint.net",
        "hwcdn.net",
        "incapdns.net",
        "instartlogic.com",
        "kxcdn.com",
        "maxcdn.com",
        "netdna-cdn.com",
        "netdna-ssl.com",
        "stackpathdns.com",
        "swiftcdn.com",
        "swiftserve.com",
        "cdninstagram.com",
        "fbcdn.net",
        "twimg.com",
        "ytimg.com",
        "ggpht.com",
        "gstatic.com",
        "googleusercontent.com",
        "bp.blogspot.com",
        "tumblr.com",
        "wordpress.com",
        "wixstatic.com",
        "squarespace.com",
        "shopify.com",
        "shopifycdn.com",
        "myshopify.com",
        "bigcommerce.com",
        "volusion.com",
        "3dcart.com",
        "ecwid.com",
        "prestashop.com",
        "magento.com",
        "woocommerce.com",
        "opencart.com",
        "zencart.com",
        "oscommerce.com",
        "xcart.com",
        "cscart.com",
        "cubecart.com",
        "pinnacle-cart.com",
        "americommerce.com",
        "bigcartel.com",
        "storenvy.com",
        "tictail.com",
        "goodsie.com",
        
        // Popup & Notification Services (30+ domains)
        "pushcrew.com",
        "pushengage.com",
        "pushwoosh.com",
        "onesignal.com",
        "subscribers.com",
        "webpushr.com",
        "pushassist.com",
        "aimtell.com",
        "truepush.com",
        "wonderpush.com",
        "pushbots.com",
        "pushalert.co",
        "pushpushgo.com",
        "pushly.com",
        "notix.io",
        "notix.co",
        "subscribers.com",
        "webpush.world",
        "pushground.com",
        "pushnami.com",
        "roost.com",
        "aimtell.com",
        "accengage.com",
        "airship.com",
        "batch.com",
        "catapush.com",
        "kumulos.com",
        "leanplum.com",
        "pushspring.com",
        "swrve.com",
        
        // Affiliate Networks (40+ domains)
        "awin1.com",
        "avantlink.com",
        "cj.com",
        "commission-junction.com",
        "dpbolvw.net",
        "emjcd.com",
        "jdoqocy.com",
        "kqzyfj.com",
        "linksynergy.com",
        "pjatr.com",
        "pjtra.com",
        "pntra.com",
        "pntrac.com",
        "pntrs.com",
        "qksrv.net",
        "shareasale.com",
        "tkqlhce.com",
        "tradedoubler.com",
        "zanox.com",
        "apmebf.com",
        "awltovhc.com",
        "ftjcfx.com",
        "lduhtrp.net",
        "ojrq.net",
        "anrdoezrs.net",
        "gopjn.com",
        "evyy.net",
        "affiliaxe.com",
        "affilinet.de",
        "afilio.com.de",
        "belboon.com",
        "clksite.com",
        "clickbank.net",
        "clickbooth.com",
        "clickpoint.com",
        "cuelinks.com",
        "daisycon.com",
        "dgm-au.com",
        "effiliation.com",
        "everflow.io",
        
        // Cookie Consent & GDPR (20+ domains)
        "cookiebot.com",
        "cookielaw.org",
        "onetrust.com",
        "trustarc.com",
        "truste.com",
        "evidon.com",
        "ghostery.com",
        "quantcast.com",
        "quantcast.mgr.consensu.org",
        "consensu.org",
        "consentmanager.net",
        "cookieinformation.com",
        "cookiepro.com",
        "didomi.io",
        "iubenda.com",
        "osano.com",
        "privacymanager.io",
        "sourcepoint.com",
        "termly.io",
        "usercentrics.com",
        
        // Heatmaps & Session Recording (20+ domains)
        "hotjar.com",
        "mouseflow.com",
        "crazyegg.com",
        "luckyorange.com",
        "inspectlet.com",
        "clicktale.net",
        "sessioncam.com",
        "smartlook.com",
        "fullstory.com",
        "logrocket.com",
        "heap.io",
        "contentsquare.net",
        "quantummetric.com",
        "glassbox.com",
        "tealeaf.com",
        "decibel.com",
        "usabilla.com",
        "qualaroo.com",
        "survicate.com",
        "feedbackify.com",
        
        // A/B Testing & Optimization (20+ domains)
        "optimizely.com",
        "vwo.com",
        "abtasty.com",
        "convert.com",
        "kameleoon.com",
        "monetate.net",
        "maxymiser.net",
        "sitespect.com",
        "evergage.com",
        "dynamic-yield.com",
        "qubit.com",
        "unbounce.com",
        "instapage.com",
        "leadpages.net",
        "clickfunnels.com",
        "landingi.com",
        "getresponse.com",
        "mailchimp.com",
        "constantcontact.com",
        "aweber.com",
        
        // Live Chat & Support (20+ domains)
        "intercom.io",
        "intercom.com",
        "drift.com",
        "olark.com",
        "livechatinc.com",
        "tawk.to",
        "zendesk.com",
        "zopim.com",
        "freshchat.com",
        "crisp.chat",
        "liveperson.net",
        "liveperson.com",
        "boldchat.com",
        "snapengage.com",
        "purechat.com",
        "userlike.com",
        "tidio.com",
        "smartsupp.com",
        "chaport.com",
        "chatra.io",
        
        // Email Tracking (30+ domains)
        "mailchimp.com",
        "list-manage.com",
        "constantcontact.com",
        "aweber.com",
        "getresponse.com",
        "sendgrid.net",
        "mailgun.net",
        "postmarkapp.com",
        "mandrill.com",
        "sparkpost.com",
        "sendinblue.com",
        "mailjet.com",
        "elasticemail.com",
        "amazonses.com",
        "sendpulse.com",
        "moosend.com",
        "benchmark.email",
        "campaignmonitor.com",
        "activecampaign.com",
        "drip.com",
        "convertkit.com",
        "mailerlite.com",
        "sendy.co",
        "phplist.com",
        "mautic.org",
        "acumbamail.com",
        "emailoctopus.com",
        "omnisend.com",
        "klaviyo.com",
        "dotdigital.com",
        
        // Fingerprinting & Device ID (20+ domains)
        "fingerprintjs.com",
        "iovation.com",
        "threatmetrix.com",
        "41st.com",
        "deviceatlas.com",
        "scientiamobile.com",
        "51degrees.com",
        "akamai.com",
        "bluecava.com",
        "crosswise.com",
        "drawbridge.com",
        "tapad.com",
        "adsymptotic.com",
        "adtruth.com",
        "liveramp.com",
        "neustar.biz",
        "oracle.com",
        "acxiom.com",
        "experian.com",
        "epsilon.com",
        
        // Ad Exchanges (30+ domains)
        "adx.com",
        "admeta.com",
        "admixer.net",
        "adotmob.com",
        "adpone.com",
        "adsmarket.com",
        "adspirit.de",
        "adtelligent.com",
        "advangelists.com",
        "aerserv.com",
        "appnexus.com",
        "bidsopt.com",
        "bidtheatre.com",
        "bidvertiser.com",
        "brightroll.com",
        "buysellads.com",
        "carbonads.net",
        "chitika.com",
        "clicksor.com",
        "contextweb.com",
        "conversantmedia.com",
        "cpmstar.com",
        "exponential.com",
        "google.com/adsense",
        "infolinks.com",
        "lijit.com",
        "media.net",
        "mediaforge.com",
        "mediavine.com",
        "netseer.com",
        
        // Native Advertising (20+ domains)
        "outbrain.com",
        "taboola.com",
        "revcontent.com",
        "mgid.com",
        "content.ad",
        "adblade.com",
        "adyoulike.com",
        "nativo.com",
        "sharethrough.com",
        "triplelift.com",
        "plista.com",
        "ligatus.com",
        "gravity.com",
        "zemanta.com",
        "disqus.com/api",
        "spoutable.com",
        "engageya.com",
        "adbooth.com",
        "adpushup.com",
        "adsterra.com",
        
        // Additional Affiliate Networks (for direct link ads)
        "awin1.com",
        "cj.com",
        "shareasale.com",
        "rakuten.com",
        "impact.com",
        "pepperjam.com",
        "clickbank.net",
        
        // Mobile Ad Networks (30+ domains)
        "admob.com",
        "adcolony.com",
        "applovin.com",
        "chartboost.com",
        "fyber.com",
        "inmobi.com",
        "ironsrc.com",
        "millennialmedia.com",
        "mobfox.com",
        "mopub.com",
        "nexage.com",
        "smaato.com",
        "startapp.com",
        "supersonic.com",
        "tapjoy.com",
        "unity3d.com",
        "vungle.com",
        "admost.com",
        "adsflourish.com",
        "airpush.com",
        "appbrain.com",
        "appflood.com",
        "applifier.com",
        "appsfire.com",
        "burstly.com",
        "flurry.com",
        "greystripe.com",
        "heyzap.com",
        "jumptap.com",
        "leadbolt.com",
        "mdotm.com",
        
        // Programmatic Advertising (20+ domains)
        "33across.com",
        "adsrvr.org",
        "adswizz.com",
        "appnexus.com",
        "bidswitch.net",
        "contextweb.com",
        "criteo.com",
        "doubleverify.com",
        "iponweb.com",
        "mediamath.com",
        "openx.net",
        "pubmatic.com",
        "pulsepoint.com",
        "quantcast.com",
        "rubiconproject.com",
        "smartadserver.com",
        "sovrn.com",
        "spotx.tv",
        "teads.tv",
        "yieldmo.com",
        
        // Additional Common Ad Domains (100+ domains)
        "2o7.net",
        "3lift.com",
        "4dsply.com",
        "5min.com",
        "6sense.com",
        "a-ads.com",
        "aarki.com",
        "abmr.net",
        "acint.net",
        "actonsoftware.com",
        "ad-delivery.net",
        "ad-maven.com",
        "ad-score.com",
        "ad.gt",
        "ad120m.com",
        "ad2iction.com",
        "ad4game.com",
        "ad6media.fr",
        "adacado.com",
        "adadvisor.net",
        "adap.tv",
        "adblade.com",
        "adbooth.com",
        "adbrn.com",
        "adbutler.com",
        "adcash.com",
        "adchemy.com",
        "adclerks.com",
        "adcolony.com",
        "addthis.com",
        "addthisedge.com",
        "addtoany.com",
        "adelement.com",
        "adengage.com",
        "adentifi.com",
        "adexchangeprediction.com",
        "adextent.com",
        "adfactor.nl",
        "adforgames.com",
        "adgear.com",
        "adglare.com",
        "adgoji.com",
        "adgrx.com",
        "adhands.ru",
        "adhese.com",
        "adhigh.net",
        "adhood.com",
        "adiant.com",
        "adikteev.com",
        "adingo.jp",
        "adition.com",
        "adjug.com",
        "adjust.com",
        "adjust.io",
        "adkernel.com",
        "adknowledge.com",
        "adlabs.ru",
        "adledge.com",
        "adlooxtracking.com",
        "adlucent.com",
        "admarketplace.com",
        "admaster.com.cn",
        "admaxim.com",
        "admedia.com",
        "admedo.com",
        "admeld.com",
        "admicro.vn",
        "admin.ch",
        "admixer.co.kr",
        "admixer.net",
        "admized.com",
        "admost.com",
        "admulti.com",
        "adnanny.com",
        "adnologies.com",
        "adnow.com",
        "adobe.com",
        "adobedtm.com",
        "adocean.pl",
        "adometry.com",
        "adomik.com",
        "adonion.com",
        "adoperator.com",
        "adoric.com",
        "adorika.com",
        "adotube.com",
        "adparlor.com",
        "adperium.com",
        "adpilot.com",
        "adpixel.com",
        "adplan.ne.jp",
        "adplus.co.id",
        "adpredictive.com",
        "adprofex.com",
        "adpushup.com",
        "adreactor.com",
        "adrecord.com",
        "adrecover.com",
        "adresult.jp",
        "adroll.com",
        "adrolays.de",
        "adriver.ru",
        "adrtx.net",
        "adsbookie.com",
        "adscale.de",
        "adsco.re",
        "adscpm.com",
        "adsenseformobileapps.com",
        "adserver.com",
        "adservice.com",
        "adsfac.eu",
        "adsfac.net",
        "adsfac.us",
        "adsflourish.com",
        "adside.com",
        "adskeeper.co.uk",
        "adskom.com",
        "adslot.com",
        "adsmogo.com",
        "adsmoloco.com",
        "adsnative.com",
        "adsoptimal.com",
        "adspeed.com",
        "adspirit.de",
        "adsplay.com",
        "adspygoogle.com",
        "adstage.io",
        "adstanding.com",
        "adstir.com",
        "adstract.com",
        "adswizz.com",
        "adsymptotic.com",
        "adtaily.com",
        "adtarget.io",
        "adtarget.me",
        "adtech.de",
        "adtegrity.net",
        "adtelligent.com",
        "adtheorent.com",
        "adthrive.com",
        "adtiger.de",
        "adtilt.com",
        "adtoma.com",
        "adtraction.com",
        "adtrue.com",
        "adultadworld.com",
        "adultfriendfinder.com",
        "adux.com",
        "advance.net",
        "advancedhosting.com",
        "advark.net",
        "adventori.com",
        "adversal.com",
        "adverteerdirect.nl",
        "adverticum.net",
        "advertise.com",
        "advertisespace.com",
        "advertising.com",
        "advertlets.com",
        "advertserve.com",
        "advolution.de",
        "adwebster.com",
        "adwhirl.com",
        "adworldmedia.com",
        "adxcel.com",
        "adxcore.com",
        "adxpansion.com",
        "adxpose.com",
        "adyapper.com",
        "adyoulike.com",
        "adzerk.net",
        "adzip.co",
        "adzly.com",
        "adzones.com",
        
        // Additional Ad & Tracking Domains (125+ more to reach 1000+)
        "adzymic.com",
        "aebn.net",
        "affec.tv",
        "affinity.com",
        "aftonbladet-cdn.se",
        "agkn.com",
        "ahalogy.com",
        "aimatch.com",
        "airpr.com",
        "akamai.net",
        "akstat.io",
        "alexa.com",
        "alexametrics.com",
        "algovid.com",
        "aliexpress.com",
        "allure.com",
        "alphonso.tv",
        "amazon.com",
        "amazonpay.com",
        "amobee.com",
        "amplitude.com",
        "analytics.edgekey.net",
        "analytics.yahoo.com",
        "aol.com",
        "apester.com",
        "api.mixpanel.com",
        "apicit.net",
        "appcues.com",
        "appdynamics.com",
        "appier.net",
        "applause.com",
        "apple-cloudkit.com",
        "applovin.com",
        "appsflyer.com",
        "apptimize.com",
        "apsalar.com",
        "ard.de",
        "art19.com",
        "artofman.com",
        "arukereso.hu",
        "aspnetcdn.com",
        "assoc-amazon.com",
        "atdmt.com",
        "atlassian.net",
        "ato.mx",
        "atwola.com",
        "audience2media.com",
        "audienceinsights.net",
        "audienceproject.com",
        "audiencerate.com",
        "audiencerun.com",
        "auditude.com",
        "augur.io",
        "auth0.com",
        "automattic.com",
        "avocet.io",
        "awaps.net",
        "axill.io",
        "azureedge.net",
        "b-cdn.net",
        "b92.net",
        "baidu.com",
        "bannerflow.com",
        "bannersnack.com",
        "banzai.it",
        "batmobi.net",
        "bazaarvoice.com",
        "bbelements.com",
        "beachfront.com",
        "bebi.com",
        "beemray.com",
        "begun.ru",
        "betrad.com",
        "bfmio.com",
        "bidgear.com",
        "bidr.io",
        "bidtellect.com",
        "bing.com",
        "bingads.com",
        "bizible.com",
        "bizographics.com",
        "bkrtx.com",
        "blogads.com",
        "blogblog.com",
        "blogger.com",
        "blogherads.com",
        "blogsmithmedia.com",
        "blueconic.net",
        "bluecore.com",
        "bluefinlabs.com",
        "bluelithium.com",
        "bmmetrix.com",
        "bnc.lt",
        "boomtrain.com",
        "bouncex.net",
        "bounceexchange.com",
        "boxever.com",
        "branch.io",
        "brandmetrics.com",
        "braze.com",
        "bre.is",
        "brightcove.net",
        "brightedge.com",
        "brightroll.com",
        "bronto.com",
        "bttrack.com",
        "bugsnag.com",
        "burt.io",
        "businessinsider.com",
        "buysellads.com",
        "buzzfeed.com",
        "c1exchange.com",
        "c3metrics.com",
        "c3tag.com",
        "cadreon.com",
        "callrail.com",
        "campaignmonitor.com",
        "captify.us",
        "carbonads.com",
        "caroda.io",
        "casalemedia.com",
        "cedexis.com",
        "celtra.com",
        "centraltag.com",
        "certona.net",
        "channeladvisor.com",
        "chartbeat.net",
        "chatra.com",
        "cheqzone.com",
        "chitika.net",
        "choicestream.com",
        "clarity.ms"
    )
    
    /**
     * List of common ad URL patterns and keywords.
     * Used for pattern matching in URLs.
     * 
     * ============================================================================
     * CUSTOMIZATION: Adding Custom Ad Keywords
     * ============================================================================
     * Add URL patterns and keywords that commonly appear in ad/tracking URLs.
     * 
     * Pattern types:
     * 1. Path patterns: "/ads/", "/banner/", "/tracking/"
     * 2. Domain patterns: "doubleclick", "adsystem", "analytics"
     * 3. Query parameters: "ad_id=", "utm_source=", "gclid="
     * 
     * Example additions:
     * ```kotlin
     * // Path patterns
     * "/custom-ads/",
     * "/my-tracking/",
     * 
     * // Domain patterns
     * "mycompany-ads",
     * "custom-tracker",
     * 
     * // Query parameters
     * "my_campaign_id=",
     * "custom_ref=",
     * ```
     * 
     * Tips:
     * - Use lowercase for case-insensitive matching
     * - Be specific to avoid false positives
     * - Test thoroughly - generic keywords may block legitimate content
     * - Patterns are checked with .contains(), so "ads" will match "ads", "advertisements", etc.
     * 
     * Warning: Overly broad keywords (e.g., "ad", "track") may block legitimate URLs.
     * Always test after adding new keywords.
     * ============================================================================
     */
    val adKeywords: List<String> = listOf(
        // Path-based patterns
        "/ads/",
        "/ad/",
        "/advert",
        "/advertising",
        "/banner",
        "/banners",
        "/sponsor",
        "/sponsored",
        "/popup",
        "/popunder",
        "/tracking",
        "/tracker",
        "/analytics",
        "/beacon",
        "/pixel",
        "/impression",
        "/click",
        "/adserver",
        "/adservice",
        "/adsystem",
        "/adtech",
        "/adview",
        "/pagead",
        "/adfarm",
        "/adframe",
        "/adimage",
        "/adjs",
        "/adlog",
        "/admanager",
        "/adnetwork",
        "/adpixel",
        "/adrequest",
        "/adscript",
        "/adserving",
        "/adshow",
        "/adspace",
        "/adstream",
        "/adtag",
        "/adtrack",
        "/adunit",
        "/adzone",
        
        // Direct link ad patterns (sponsored content)
        "/sponsored/",
        "/sponsor/",
        "/sp/",
        "/spon/",
        "/advertisement/",
        "/promo/",
        "/promotional/",
        "/promotion/",
        
        // Affiliate and tracking patterns
        "/aff_c",
        "/affiliate/",
        "/aff/",
        "/partner/",
        "/track/",
        "/click/",
        "/clk/",
        "/redirect/",
        "/redir/",
        "/go/",
        "/out/",
        "/exit/",
        "/away/",
        "/link/",
        
        // Native ad networks
        "outbrain",
        "taboola",
        "revcontent",
        "mgid",
        "zergnet",
        "bidvertiser",
        "nativead",
        "native-ad",
        
        // Click tracking
        "clicktrack",
        "adclick",
        "adsclick",
        "impression",
        "/imp/",
        "/beacon/",
        "/event/",
        "/pixel",
        
        // Domain/subdomain patterns
        "doubleclick",
        "adsystem",
        "adservice",
        "adserver",
        "pagead",
        "analytics",
        "tracking",
        "tracker",
        "pixel",
        "beacon",
        "telemetry",
        "metrics",
        "stats",
        "counter",
        "impression",
        "clicktrack",
        "adtech",
        "adnetwork",
        "adexchange",
        "adsense",
        "admob",
        "adwords",
        "syndication",
        "monetize",
        "affiliate",
        "referral",
        "campaign",
        "promo",
        "marketing",
        "retarget",
        "remarketing",
        
        // Query parameter patterns
        "ad_id=",
        "ad_type=",
        "adid=",
        "adunit=",
        "banner_id=",
        "campaign_id=",
        "click_id=",
        "clickid=",
        "gclid=",
        "fbclid=",
        "msclkid=",
        "utm_source=",
        "utm_medium=",
        "utm_campaign=",
        "utm_content=",
        "utm_term=",
        "ref=",
        "referrer=",
        "affiliate=",
        "aff_id=",
        "tracking_id=",
        "tracker_id=",
        
        // Additional affiliate markers
        "?aff=",
        "&aff=",
        "?affiliate=",
        "&affiliate=",
        "ref=sponsored",
        "ref=partner",
        "ref=affiliate",
        
        // Direct link ad patterns (click hijacking)
        "/redirect?",
        "/redir?",
        "/go?",
        "/out?",
        "/away?",
        "/exit?",
        "/click?",
        "/clk?",
        "/track?",
        "?url=http",
        "&url=http",
        "?link=http",
        "&link=http",
        "?dest=http",
        "&dest=http",
        "?target=http",
        "&target=http",
        "?redirect=http",
        "&redirect=http",
        "?r=http",
        "&r=http",
        "?goto=http",
        "&goto=http",
        "?next=http",
        "&next=http",
        "?continue=http",
        "&continue=http",
        "?return=http",
        "&return=http",
        "?adurl=",
        "&adurl=",
        "?click_url=",
        "&click_url=",
        "?clickurl=",
        "&clickurl=",
        
        // Streaming site ad patterns
        "/player/ad",
        "/embed/ad",
        "/watch/ad",
        "/video/ad",
        "?zoneid=",
        "&zoneid=",
        "?subid=",
        "&subid=",
        "?clickid=",
        "&clickid=",
        "?click_id=",
        "&click_id=",
        
        // Pop-up/Pop-under patterns
        "popunder",
        "popup",
        "pop-up",
        "pop_up",
        "popads",
        "popcash",
        "popwin",
        "popnew",
        
        // Interstitial patterns
        "interstitial",
        "splash",
        "landing",
        "offer",
        "promo",
        
        // CPA/CPC/CPM patterns
        "/cpa/",
        "/cpc/",
        "/cpm/",
        "/ppc/",
        "/ppl/"
    )
    
    /**
     * Path segment patterns for direct link ads
     */
    private val suspiciousPathPatterns = listOf(
        "sponsor", "sponsored", "promo", "promotional",
        "advertisement", "affiliate", "partner", "campaign",
        "redirect", "click", "tracker", "tracking"
    )
    
    /**
     * Checks if a URL should be blocked based on hardcoded filters.
     * 
     * @param url The URL to check
     * @return true if the URL should be blocked, false otherwise
     */
    // Essential Google domains that should NEVER be blocked
    // These serve legitimate content for Google Search, Images, etc.
    private val googleWhitelist = setOf(
        "www.google.com",
        "google.com/search",
        "google.com/images",
        "encrypted-tbn",  // Google Images thumbnails
        "gstatic.com",    // Google static content (CSS, JS, images)
        "googleusercontent.com",  // User-uploaded content
        "ggpht.com",      // Google profile photos
        "googleapis.com", // Google APIs (fonts, maps, etc.)
        "accounts.google.com",
        "play.google.com"
    )
    
    private fun isGoogleWhitelisted(url: String): Boolean {
        return googleWhitelist.any { url.contains(it) }
    }
    
    fun shouldBlock(url: String): Boolean {
        try {
            val lowerUrl = url.lowercase()
            
            // WHITELIST CHECK: Never block essential Google domains
            if (isGoogleWhitelisted(lowerUrl)) {
                return false
            }
            
            // Check if URL contains any blocked domain
            for (domain in adDomains) {
                if (lowerUrl.contains(domain)) {
                    return true
                }
            }
            
            // Check if URL contains any ad keyword
            for (keyword in adKeywords) {
                if (lowerUrl.contains(keyword)) {
                    return true
                }
            }
            
            // Check path segments for suspicious patterns
            if (hasSuspiciousPath(lowerUrl)) {
                return true
            }
            
            // Check for excessive tracking parameters
            if (hasExcessiveTrackingParams(lowerUrl)) {
                return true
            }
            
            return false
        } catch (e: Exception) {
            // On error, allow the request (fail gracefully)
            return false
        }
    }
    
    /**
     * Check if URL path contains suspicious ad-related segments
     */
    private fun hasSuspiciousPath(url: String): Boolean {
        try {
            val pathStart = url.indexOf("://")
            if (pathStart == -1) return false
            
            val afterProtocol = url.substring(pathStart + 3)
            val pathStartIndex = afterProtocol.indexOf("/")
            if (pathStartIndex == -1) return false
            
            val path = afterProtocol.substring(pathStartIndex)
            val segments = path.split("/", "?", "&")
            
            for (segment in segments) {
                for (pattern in suspiciousPathPatterns) {
                    if (segment.contains(pattern)) {
                        return true
                    }
                }
            }
        } catch (e: Exception) {
            // Skip on error
        }
        
        return false
    }
    
    /**
     * Check if URL has excessive tracking parameters (likely an ad)
     */
    private fun hasExcessiveTrackingParams(url: String): Boolean {
        val trackingParams = listOf(
            "utm_source", "utm_medium", "utm_campaign", "utm_content", "utm_term",
            "ref", "source", "medium", "campaign", "fbclid", "gclid",
            "msclkid", "mc_cid", "mc_eid"
        )
        
        var count = 0
        for (param in trackingParams) {
            if (url.contains(param)) {
                count++
            }
        }
        
        // If URL has 3+ tracking parameters, it's likely a tracked ad link
        return count >= 3
    }
}
